version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__SQLDbConnection: "Server=host.docker.internal,1433;Initial Catalog=CommandDb;TrustServerCertificate=True"
      ConnectionStrings__UserID: "sa"
      ConnectionStrings__Password: "pa55w0rd!"

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "pa55w0rd!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
